### ISSUE TITLE
Function meta FORTH flow control

### ISSUE THREAD

**Issue by zignig** [HackerFoo/poprc#3]
is this a structurally different flow language?

**Comment by HackerFoo** [comment]
@zignig If you still have a question, could you please clarify it? Is it about [metacompilation](https://en.wikipedia.org/wiki/Metacompilation)? PoprC uses similar techniques based on partial evaluation, along with unification on recursion to implement a form of deforestation.

**Comment by zignig** [comment]
I have been noodling around with Forth for a few years and am currently investigating FPGA processors.  

Popr appears to be a interesting alternative at the low level, It would be nice to see some more concrete examples of process. 

My other more forth related question is, have you though about a tiny poprc vm ? fitting the entire basis into a few K of a microcontroller ?

**Comment by HackerFoo** [comment]
There are several examples with testbenches in the `testbenches` directory in the repo. You can run them all by running `make` in that directory, and inspect the traces (.fst) with GTKWave in the resulting `testbenches/build/sim` directory. I'll add more testbenches as I implement more features.

Why implement a VM rather than targeting a real machine? If the concern is code size, I haven't really optimized for that yet. PoprC does have it's own graph reduction machine, but this isn't really suitable for runtime, even though it's pretty well optimized. It's designed for tracing programs for partial evaluation.
